### ISSUE TITLE
Gitignore-fil saknas

### ISSUE THREAD

**Issue by johber** [TonyKarlsson/ZombieWars#1]
Bland de incheckade filerna finns bygg-filer (bin-mappen) och användarfiler (.vscode, .DS_Store) Lägg till en .gitignore-fil som anger vad som inte ska versioneras.

Länkförslag:
https://git-scm.com/docs/gitignore
https://github.com/dotnet/core/blob/main/.gitignore

**Comment by TonyKarlsson** [comment]
Jag valde att inte ha en .gitignore då jag för tillfället inte behöver en sån. Men kanske bra att ta med en ändå...
